<?php

namespace ContainerWCjsmTD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminDashboardControllercancelRendezvousService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PkcWAWa.App\Controller\AdminDashboardController::cancelRendezvous()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PkcWAWa.App\\Controller\\AdminDashboardController::cancelRendezvous()'] = ($container->privates['.service_locator.PkcWAWa'] ?? $container->load('get_ServiceLocator_PkcWAWaService'))->withContext('App\\Controller\\AdminDashboardController::cancelRendezvous()', $container);
    }
}
