<?php

namespace ContainerWCjsmTD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lwer3Oe.App\Controller\CartController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.lwer3Oe'] ?? $container->load('get_ServiceLocator_Lwer3OeService'));

        if (isset($container->privates['.service_locator.lwer3Oe.App\\Controller\\CartController::new()'])) {
            return $container->privates['.service_locator.lwer3Oe.App\\Controller\\CartController::new()'];
        }

        return $container->privates['.service_locator.lwer3Oe.App\\Controller\\CartController::new()'] = $a->withContext('App\\Controller\\CartController::new()', $container);
    }
}
