<?php

namespace ContainerWCjsmTD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMotorisationControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xZ1H0Mt.App\Controller\MotorisationController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xZ1H0Mt.App\\Controller\\MotorisationController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'motorisation' => ['privates', '.errored..service_locator.xZ1H0Mt.App\\Entity\\Motorisation', NULL, 'Cannot autowire service ".service_locator.xZ1H0Mt": it needs an instance of "App\\Entity\\Motorisation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'motorisation' => 'App\\Entity\\Motorisation',
        ]))->withContext('App\\Controller\\MotorisationController::show()', $container);
    }
}
