<?php

namespace ContainerWCjsmTD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModeleControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5UfiEs7.App\Controller\ModeleController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.5UfiEs7'] ?? $container->load('get_ServiceLocator_5UfiEs7Service'));

        if (isset($container->privates['.service_locator.5UfiEs7.App\\Controller\\ModeleController::edit()'])) {
            return $container->privates['.service_locator.5UfiEs7.App\\Controller\\ModeleController::edit()'];
        }

        return $container->privates['.service_locator.5UfiEs7.App\\Controller\\ModeleController::edit()'] = $a->withContext('App\\Controller\\ModeleController::edit()', $container);
    }
}
