<?php

namespace ContainerWCjsmTD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModeleControllergetModelsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FZhUcSf.App\Controller\ModeleController::getModels()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FZhUcSf.App\\Controller\\ModeleController::getModels()'] = ($container->privates['.service_locator.FZhUcSf'] ?? $container->load('get_ServiceLocator_FZhUcSfService'))->withContext('App\\Controller\\ModeleController::getModels()', $container);
    }
}
