<?php

namespace ContainerWCjsmTD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllerconfirmationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KyJldkg.App\Controller\OrderController::confirmation()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KyJldkg.App\\Controller\\OrderController::confirmation()'] = ($container->privates['.service_locator.KyJldkg'] ?? $container->load('get_ServiceLocator_KyJldkgService'))->withContext('App\\Controller\\OrderController::confirmation()', $container);
    }
}
