<?php

namespace ContainerWCjsmTD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lwer3Oe.App\Controller\OrderController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lwer3Oe.App\\Controller\\OrderController::new()'] = ($container->privates['.service_locator.lwer3Oe'] ?? $container->load('get_ServiceLocator_Lwer3OeService'))->withContext('App\\Controller\\OrderController::new()', $container);
    }
}
