<?php

namespace ContainerWCjsmTD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubCategoryControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rudU.bo.App\Controller\SubCategoryController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rudU.bo.App\\Controller\\SubCategoryController::delete()'] = ($container->privates['.service_locator.rudU.bo'] ?? $container->load('get_ServiceLocator_RudU_BoService'))->withContext('App\\Controller\\SubCategoryController::delete()', $container);
    }
}
