<?php

namespace ContainerWCjsmTD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVehicleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3RPStPZ.App\Entity\Vehicle' shared service.
     *
     * @return \App\Entity\Vehicle
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3RPStPZ": it needs an instance of "App\\Entity\\Vehicle" but this type has been excluded in "config/services.yaml".');
    }
}
