<?php

namespace ContainerQHZjSox;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockMovementControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HZT2Ves.App\Controller\StockMovementController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HZT2Ves.App\\Controller\\StockMovementController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'stockMovement' => ['privates', '.errored..service_locator.HZT2Ves.App\\Entity\\StockMovement', NULL, 'Cannot autowire service ".service_locator.HZT2Ves": it needs an instance of "App\\Entity\\StockMovement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'stockMovement' => 'App\\Entity\\StockMovement',
        ]))->withContext('App\\Controller\\StockMovementController::show()', $container);
    }
}
