<?php

namespace ContainerQHZjSox;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVehicleControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cAjDidu.App\Controller\VehicleController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cAjDidu.App\\Controller\\VehicleController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'vehicle' => ['privates', '.errored..service_locator.cAjDidu.App\\Entity\\Vehicle', NULL, 'Cannot autowire service ".service_locator.cAjDidu": it needs an instance of "App\\Entity\\Vehicle" but this type has been excluded in "config/services.yaml".'],
        ], [
            'vehicle' => 'App\\Entity\\Vehicle',
        ]))->withContext('App\\Controller\\VehicleController::show()', $container);
    }
}
