<?php

namespace ContainerWmPPyxv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LFy6oZRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lFy6oZR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lFy6oZR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'stockMovement' => ['privates', '.errored..service_locator.lFy6oZR.App\\Entity\\StockMovement', NULL, 'Cannot autowire service ".service_locator.lFy6oZR": it needs an instance of "App\\Entity\\StockMovement" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'stockMovement' => 'App\\Entity\\StockMovement',
            'entityManager' => '?',
        ]);
    }
}
