<?php

namespace ContainerWmPPyxv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5UfiEs7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5UfiEs7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5UfiEs7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'modele' => ['privates', '.errored..service_locator.5UfiEs7.App\\Entity\\Modele', NULL, 'Cannot autowire service ".service_locator.5UfiEs7": it needs an instance of "App\\Entity\\Modele" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'modele' => 'App\\Entity\\Modele',
            'entityManager' => '?',
        ]);
    }
}
