<?php

namespace ContainerWmPPyxv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppointmentControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CW7CnPW.App\Controller\AppointmentController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.CW7CnPW'] ?? $container->load('get_ServiceLocator_CW7CnPWService'));

        if (isset($container->privates['.service_locator.CW7CnPW.App\\Controller\\AppointmentController::edit()'])) {
            return $container->privates['.service_locator.CW7CnPW.App\\Controller\\AppointmentController::edit()'];
        }

        return $container->privates['.service_locator.CW7CnPW.App\\Controller\\AppointmentController::edit()'] = $a->withContext('App\\Controller\\AppointmentController::edit()', $container);
    }
}
