<?php

namespace ContainerWmPPyxv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminDashboardControllermanageVehiclesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i2WvvtF.App\Controller\AdminDashboardController::manageVehicles()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i2WvvtF.App\\Controller\\AdminDashboardController::manageVehicles()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'marqueRepository' => ['privates', 'App\\Repository\\MarqueRepository', 'getMarqueRepositoryService', true],
            'modeleRepository' => ['privates', 'App\\Repository\\ModeleRepository', 'getModeleRepositoryService', true],
            'motorisationRepository' => ['privates', 'App\\Repository\\MotorisationRepository', 'getMotorisationRepositoryService', true],
        ], [
            'entityManager' => '?',
            'marqueRepository' => 'App\\Repository\\MarqueRepository',
            'modeleRepository' => 'App\\Repository\\ModeleRepository',
            'motorisationRepository' => 'App\\Repository\\MotorisationRepository',
        ]))->withContext('App\\Controller\\AdminDashboardController::manageVehicles()', $container);
    }
}
