<?php

namespace ContainerWmPPyxv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminDashboardControllermanageOrdersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aIFUyYq.App\Controller\AdminDashboardController::manageOrders()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aIFUyYq.App\\Controller\\AdminDashboardController::manageOrders()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'orderRepository' => 'App\\Repository\\OrderRepository',
            'entityManager' => '?',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\AdminDashboardController::manageOrders()', $container);
    }
}
