<?php

namespace ContainerWmPPyxv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMotorisationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ijeeteN.App\Entity\Motorisation' shared service.
     *
     * @return \App\Entity\Motorisation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ijeeteN": it needs an instance of "App\\Entity\\Motorisation" but this type has been excluded in "config/services.yaml".');
    }
}
