<?php

namespace ContainerWmPPyxv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModele2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.UXE8nMY.App\Entity\Modele' shared service.
     *
     * @return \App\Entity\Modele
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.UXE8nMY": it needs an instance of "App\\Entity\\Modele" but this type has been excluded in "config/services.yaml".');
    }
}
