<?php

namespace ContainerWmPPyxv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMotorisationControllergetMotorisationsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qSsdLYY.App\Controller\MotorisationController::getMotorisations()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qSsdLYY.App\\Controller\\MotorisationController::getMotorisations()'] = ($container->privates['.service_locator.qSsdLYY'] ?? $container->load('get_ServiceLocator_QSsdLYYService'))->withContext('App\\Controller\\MotorisationController::getMotorisations()', $container);
    }
}
