<?php

namespace ContainerWmPPyxv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModeleControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UXE8nMY.App\Controller\ModeleController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UXE8nMY.App\\Controller\\ModeleController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'modele' => ['privates', '.errored..service_locator.UXE8nMY.App\\Entity\\Modele', NULL, 'Cannot autowire service ".service_locator.UXE8nMY": it needs an instance of "App\\Entity\\Modele" but this type has been excluded in "config/services.yaml".'],
        ], [
            'modele' => 'App\\Entity\\Modele',
        ]))->withContext('App\\Controller\\ModeleController::show()', $container);
    }
}
