<?php

namespace ContainerWmPPyxv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LEf9U9t.App\Controller\OrderController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.LEf9U9t'] ?? $container->load('get_ServiceLocator_LEf9U9tService'));

        if (isset($container->privates['.service_locator.LEf9U9t.App\\Controller\\OrderController::edit()'])) {
            return $container->privates['.service_locator.LEf9U9t.App\\Controller\\OrderController::edit()'];
        }

        return $container->privates['.service_locator.LEf9U9t.App\\Controller\\OrderController::edit()'] = $a->withContext('App\\Controller\\OrderController::edit()', $container);
    }
}
