<?php

namespace ContainerWmPPyxv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockMovementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HZT2Ves.App\Entity\StockMovement' shared service.
     *
     * @return \App\Entity\StockMovement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.HZT2Ves": it needs an instance of "App\\Entity\\StockMovement" but this type has been excluded in "config/services.yaml".');
    }
}
