<?php

namespace ContainerWmPPyxv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Oa0Xz2V.App\Entity\SubCategory' shared service.
     *
     * @return \App\Entity\SubCategory
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Oa0Xz2V": it needs an instance of "App\\Entity\\SubCategory" but this type has been excluded in "config/services.yaml".');
    }
}
