<?php

namespace ContainerYygPqgA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppointmentControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ufQKqF0.App\Controller\AppointmentController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ufQKqF0.App\\Controller\\AppointmentController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'appointmentRepository' => ['privates', 'App\\Repository\\AppointmentRepository', 'getAppointmentRepositoryService', true],
        ], [
            'appointmentRepository' => 'App\\Repository\\AppointmentRepository',
        ]))->withContext('App\\Controller\\AppointmentController::index()', $container);
    }
}
