<?php

namespace ContainerYygPqgA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminDashboardControllervalidateRendezvousService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PkcWAWa.App\Controller\AdminDashboardController::validateRendezvous()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.PkcWAWa'] ?? $container->load('get_ServiceLocator_PkcWAWaService'));

        if (isset($container->privates['.service_locator.PkcWAWa.App\\Controller\\AdminDashboardController::validateRendezvous()'])) {
            return $container->privates['.service_locator.PkcWAWa.App\\Controller\\AdminDashboardController::validateRendezvous()'];
        }

        return $container->privates['.service_locator.PkcWAWa.App\\Controller\\AdminDashboardController::validateRendezvous()'] = $a->withContext('App\\Controller\\AdminDashboardController::validateRendezvous()', $container);
    }
}
