<?php

namespace ContainerYygPqgA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LEf9U9t.App\Controller\OrderController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LEf9U9t.App\\Controller\\OrderController::delete()'] = ($container->privates['.service_locator.LEf9U9t'] ?? $container->load('get_ServiceLocator_LEf9U9tService'))->withContext('App\\Controller\\OrderController::delete()', $container);
    }
}
