<?php

namespace ContainerYygPqgA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVehicleControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3RPStPZ.App\Controller\VehicleController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3RPStPZ.App\\Controller\\VehicleController::delete()'] = ($container->privates['.service_locator.3RPStPZ'] ?? $container->load('get_ServiceLocator_3RPStPZService'))->withContext('App\\Controller\\VehicleController::delete()', $container);
    }
}
