<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWCjsmTD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWCjsmTD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWCjsmTD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWCjsmTD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWCjsmTD\App_KernelDevDebugContainer([
    'container.build_hash' => 'WCjsmTD',
    'container.build_id' => '5867a756',
    'container.build_time' => 1737039551,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWCjsmTD');
